# Generated by Django 3.2 on 2021-07-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lightapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='telephoneurgencepatient',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero urgence patient'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='codepatient',
            field=models.CharField(default='MED-2021-00953007-032133', max_length=255, verbose_name='Code'),
        ),
    ]
