# Generated by Django 3.2 on 2021-07-04 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lightapp', '0002_auto_20210704_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='codepatient',
            field=models.CharField(default='MED-2021-01532107-439175', max_length=255, verbose_name='Code'),
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praticien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Praticien')),
                ('dateprevu', models.DateField(default=django.utils.timezone.now, verbose_name='Date RDV')),
                ('heuredebut', models.TimeField(blank=True, null=True, verbose_name='Heure debut')),
                ('servicerdv', models.CharField(blank=True, max_length=255, null=True, verbose_name='Service')),
                ('duree', models.IntegerField(blank=True, default=0, null=True, verbose_name='Duree')),
                ('actesrdv', models.TextField(blank=True, null=True, verbose_name='Service')),
                ('prioriterdv', models.CharField(choices=[('Normal', 'Normal'), ('Urgences', 'Urgences')], default='Normal', max_length=255, verbose_name='Priorite')),
                ('typerdv', models.CharField(choices=[('Normal', 'Normal'), ('Contrôle', 'Contrôle')], default='Normal', max_length=255, verbose_name='Type RDV')),
                ('statut', models.CharField(choices=[('A effectué', 'A effectué'), ('Effectué', 'Effectué')], default='A effectué', max_length=255, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('archive', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv', to='Lightapp.patients')),
            ],
            options={
                'ordering': ('dateprevu', 'heuredebut'),
            },
        ),
        migrations.CreateModel(
            name='Paiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datepaiement', models.DateField(default=django.utils.timezone.now, verbose_name='Date paiement')),
                ('heurepaiement', models.TimeField(default=django.utils.timezone.now, verbose_name='Date paiement')),
                ('totalpaiement', models.IntegerField(default=0, verbose_name='Total paiement')),
                ('praticien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Praticien')),
                ('archive', models.BooleanField(default=False)),
                ('Statut', models.CharField(choices=[('Ouverte', 'Ouverte'), ('Payée', 'Payée'), ('Annulée', 'Annulée')], default='Ouverte', max_length=255, verbose_name='Statut')),
                ('caisse', models.BooleanField(default=False)),
                ('servicepaiement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Service')),
                ('actespaiement', models.TextField(blank=True, null=True, verbose_name='Actes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paiement', to='Lightapp.patients')),
            ],
            options={
                'ordering': ('datepaiement', 'heurepaiement'),
            },
        ),
    ]
